#!/usr/bin/env bash
set -euo pipefail

ROOT="${BMAD_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
ORCH_DIR="$ROOT/_bmad-output/orchestration"
PROMPT="$ORCH_DIR/orchestrator-prompt.md"
LOG_DIR="$ORCH_DIR/logs"
RUNTIME_STATE="$ORCH_DIR/runtime-state.yaml"
STOP_FILE="$ORCH_DIR/STOP"
LOCK_FILE="$ORCH_DIR/.bmad-implementation-loop.lock"
AGENT_CLI="${BMAD_AGENT_CLI:-opencode}"
ORCHESTRATOR_MODEL="${BMAD_ORCHESTRATOR_MODEL:-${BMAD_CODEX_MODEL:-openrouter/@preset/el-cheapo}}"
DELEGATE_MODEL="${BMAD_DELEGATE_MODEL:-openrouter/@preset/el-cheapo}"
SLEEP_SECONDS="${BMAD_LOOP_SLEEP_SECONDS:-600}"
ONCE=0

usage() {
  cat <<'USAGE'
Usage: scripts/bmad-implementation-loop.sh [--once]

Runs the BMAD implementation orchestrator loop.

Environment:
  BMAD_AGENT_CLI           Agent CLI to run. Default: opencode
  BMAD_ORCHESTRATOR_MODEL  Model passed to the orchestrator. Default: openrouter/@preset/el-cheapo
  BMAD_DELEGATE_MODEL      Required delegated worker model. Default: openrouter/@preset/el-cheapo
  BMAD_CODEX_MODEL         Legacy alias for BMAD_ORCHESTRATOR_MODEL.
  BMAD_LOOP_SLEEP_SECONDS  Delay between passes. Default: 600
  BMAD_ROOT                Repository root override.
USAGE
}

while (($#)); do
  case "$1" in
    --once)
      ONCE=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

mkdir -p "$LOG_DIR"

if [[ ! -f "$PROMPT" ]]; then
  echo "Missing orchestrator prompt: $PROMPT" >&2
  exit 1
fi

exec 9>"$LOCK_FILE"
if ! flock -n 9; then
  echo "BMAD implementation loop is already running: $LOCK_FILE" >&2
  exit 1
fi

write_runtime_state() {
  local status="$1"
  local pass="$2"
  local log_path="$3"
  local last_message="$4"
  local timestamp
  timestamp="$(date -Is)"

  cat >"$RUNTIME_STATE" <<STATE
# Generated by scripts/bmad-implementation-loop.sh
last_updated: $timestamp
project: skillex
root: $ROOT
status: $status
agent_cli: $AGENT_CLI
orchestrator_model: $ORCHESTRATOR_MODEL
delegate_model: $DELEGATE_MODEL
runner_pid: $$
zellij_session: ${ZELLIJ_SESSION_NAME:-unknown}
pass: $pass
last_log: $log_path
last_message: $last_message
stop_sentinel: $STOP_FILE
sleep_seconds: $SLEEP_SECONDS
STATE
}

append_loop_log() {
  local message="$1"
  printf '%s %s\n' "$(date -Is)" "$message" >>"$LOG_DIR/loop.log"
}

PASS=0
extract_last_message() {
  local log_path="$1"
  local last_message="$2"

  python3 - "$log_path" "$last_message" <<'PY'
import json
import sys
from pathlib import Path

log_path = Path(sys.argv[1])
last_message = Path(sys.argv[2])
texts = []

if log_path.exists():
    for line in log_path.read_text(errors="replace").splitlines():
        try:
            event = json.loads(line)
        except json.JSONDecodeError:
            continue
        if event.get("type") == "text":
            part = event.get("part") or {}
            text = part.get("text")
            if text:
                texts.append(text)

last_message.write_text("\n".join(texts).strip() + ("\n" if texts else ""))
PY
}

append_loop_log "loop-start cli=$AGENT_CLI orchestrator_model=$ORCHESTRATOR_MODEL delegate_model=$DELEGATE_MODEL root=$ROOT once=$ONCE"
write_runtime_state "running" "$PASS" "" ""

while true; do
  if [[ -f "$STOP_FILE" ]]; then
    append_loop_log "stop-sentinel-found path=$STOP_FILE"
    write_runtime_state "stopped" "$PASS" "" ""
    exit 0
  fi

  PASS=$((PASS + 1))
  STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
  PASS_LOG="$LOG_DIR/pass-$STAMP.log"
  LAST_MESSAGE="$LOG_DIR/pass-$STAMP.last.md"

  append_loop_log "pass-start pass=$PASS log=$PASS_LOG"

  if [[ "$AGENT_CLI" != "opencode" ]]; then
    echo "Unsupported BMAD_AGENT_CLI: $AGENT_CLI" >"$PASS_LOG"
    extract_last_message "$PASS_LOG" "$LAST_MESSAGE"
    append_loop_log "pass-complete pass=$PASS status=failed unsupported_cli=$AGENT_CLI log=$PASS_LOG"
    write_runtime_state "failed" "$PASS" "$PASS_LOG" "$LAST_MESSAGE"
    exit 2
  fi

  if opencode run \
    --dir "$ROOT" \
    --model "$ORCHESTRATOR_MODEL" \
    --dangerously-skip-permissions \
    --format json \
    --file "$PROMPT" \
    -- \
    "Run one BMAD implementation orchestrator pass using the attached prompt file. Follow it exactly. Do not ask questions; decide directly, consult experts, delegate, or record idle/blocked as instructed." \
    >"$PASS_LOG" 2>&1; then
    extract_last_message "$PASS_LOG" "$LAST_MESSAGE"
    append_loop_log "pass-complete pass=$PASS status=ok log=$PASS_LOG last_message=$LAST_MESSAGE"
    write_runtime_state "idle" "$PASS" "$PASS_LOG" "$LAST_MESSAGE"
  else
    STATUS=$?
    extract_last_message "$PASS_LOG" "$LAST_MESSAGE"
    append_loop_log "pass-complete pass=$PASS status=failed exit=$STATUS log=$PASS_LOG last_message=$LAST_MESSAGE"
    if grep -Eqi "ProviderModelNotFoundError|No LLM provider configured|401|unauthorized|invalid.*key|authentication|auth" "$PASS_LOG"; then
      append_loop_log "loop-exit status=auth-or-model-blocked model=$ORCHESTRATOR_MODEL"
      write_runtime_state "auth-or-model-blocked" "$PASS" "$PASS_LOG" "$LAST_MESSAGE"
      exit "$STATUS"
    fi
    write_runtime_state "failed" "$PASS" "$PASS_LOG" "$LAST_MESSAGE"
  fi

  if [[ "$ONCE" == "1" ]]; then
    append_loop_log "loop-exit once=1"
    exit 0
  fi

  if [[ -f "$STOP_FILE" ]]; then
    append_loop_log "stop-sentinel-found-before-sleep path=$STOP_FILE"
    write_runtime_state "stopped" "$PASS" "$PASS_LOG" "$LAST_MESSAGE"
    exit 0
  fi

  append_loop_log "sleep seconds=$SLEEP_SECONDS"
  sleep "$SLEEP_SECONDS"
done
